const Strings = {
    Common: {
        SUCCESS: "Thành Công",
        ERROR: "Có Lỗi Xảy ra",
        UNAUTHENTICATED: "Xác Thực Thất Bại",
        ERROR_PASSWORD_USERID: "Tài Khoản Hoặc Mật Khẩu Không Chính Xác",
        ERROR_SERVER: "Lỗi Máy Chủ",
        ERROR_CLIENT: "Lỗi Máy Khách",
        NOT_ENOUGH_DATA: "Không Đủ Dữ Liệu",
        SERVICE_UNAVAILABLE: "Máy Chủ Không Có Sẵn",
        ERROR_GET_DATA: "Lỗi Lấy Dữ Liệu",
        YOUR_LOGIN_SESSION_EXPIRED: "Phiên Đăng Nhập Của Bạn Đã Hết Hạn",
        NOT_PERMISSION_ACCESS: "Không Có Quyền Truy Cập",
        USER_NOT_EXIST: "Người Dùng Không Tồn Tại",
        DUPLICATE_SCHEDULE: "Lịch Trình Bị Trùng Lặp",
        INVALID_DATE: "Ngày Không Hợp Lệ",
        INVALID_REQUEST: "Yêu Cầu Không Hợp Lệ",
        INVALID_DATA: "Dữ Liệu Không Hợp Lệ",
        SIGN_UP_SUCCESS: "Đăng Ký Thành Công",
        UPDATE_SUCCESS: "Cập Nhật Thành Công",
        UPDATE_PHONE_NUMBER_SUCCESS: "Cập Nhật Số Điện Thoại Thành Công",
        CANCEL_SUCCESSFUL_REGISTRATION: "Hủy Đăng Ký Thành Công",
        LIMIT_PART_COUNT: "Ảnh Quá Nhiều Phần",
        LIMIT_FILE_SIZE: "Ảnh Quá Lớn",
        LIMIT_FILE_COUNT: "Quá Nhiều Ảnh",
        LIMIT_FIELD_KEY: "Tên Trường Quá Dài",
        LIMIT_FIELD_VALUE: "Giá Trị Trường Quá Dài",
        LIMIT_FIELD_COUNT: "Quá Nhiều Trường",
        LIMIT_UNEXPECTED_FILE: "Trường Không Mong Đợi",
        MISSING_FIELD_NAME: "Thiếu Tên Trường",
        ONLY_SUPPORT_IMAGE: "Chỉ Hỗ Trợ Tệp Hình Ảnh",
        ERROR_UPLOAD_IMAGE: "Lỗi Tải Ảnh",
    },
};

module.exports = {
    Strings,
};
