const { Constants } = require("./Constants");

const Strings = {
    Common: {
        SUCCESS: "Thành Công",
        ERROR: "Có Lỗi Xảy ra",
        UNAUTHENTICATED: "Xác Thực Thất Bại",
        ERROR_PASSWORD_USERID: "Tài Khoản Hoặc Mật Khẩu Không Chính Xác",
        ERROR_SERVER: "Lỗi Máy Chủ",
        ERROR_CLIENT: "Lỗi Máy Khách",
        NOT_ENOUGH_DATA: "Không Đủ Dữ Liệu",
        SERVICE_UNAVAILABLE: "Máy Chủ Không Có Sẵn",
        ERROR_GET_DATA: "Lỗi Lấy Dữ Liệu",
        YOUR_LOGIN_SESSION_EXPIRED: "Phiên Đăng Nhập Của Bạn Đã Hết Hạn",
        NOT_PERMISSION_ACCESS: "Không Có Quyền Truy Cập",
        USER_NOT_EXIST: "Người Dùng Không Tồn Tại",
        DUPLICATE_SCHEDULE: "Lịch Trình Bị Trùng Lặp",
        CAR_HAS_DUPLICATE_SCHEDULE: "Xe Bị Trùng Lịch Trình",
        INVALID_DATE: "Ngày Không Hợp Lệ",
        INVALID_REQUEST: "Yêu Cầu Không Hợp Lệ",
        INVALID_DATA: "Dữ Liệu Không Hợp Lệ",
        SIGN_UP_SUCCESS: "Đăng Ký Thành Công",
        UPDATE_SUCCESS: "Cập Nhật Thành Công",
        UPDATE_INFO_SCHEDULE_SUCCESS:
            "Cập Nhật Thông Tin Lịch Trình Thành Công",
        SCHEDULE_HAS_BEEN_APPROVED: "Lịch Trình Đã Được Phê Duyệt",
        SCHEDULE_HAS_BEEN_REFUSED: "Lịch Trình Đã Bị Từ Chối",
        CHANGED_DRIVER: "Đã Thay Đổi Tài Xế",
        UPDATE_PHONE_NUMBER_SUCCESS: "Cập Nhật Số Điện Thoại Thành Công",
        SCHEDULE_HAS_BEEN_RECEIVED: "Lịch Trình Đã Được Nhận",
        COMPLETE_SCHEDULE: "Hoàn Thành Lịch Trình",
        CURRENTLY_CANNOT_CANCEL_SCHEDULE: "Hiện Không Thể Hủy Lịch Trình",
        MOVING: "Đang Di Chuyển",
        CANCEL_SUCCESSFUL_REGISTRATION: "Hủy Đăng Ký Thành Công",
        LIMIT_PART_COUNT: "Ảnh Quá Nhiều Phần",
        LIMIT_FILE_SIZE: "Ảnh Quá Lớn",
        LIMIT_FILE_COUNT: "Quá Nhiều Ảnh",
        LIMIT_FIELD_KEY: "Tên Trường Quá Dài",
        LIMIT_FIELD_VALUE: "Giá Trị Trường Quá Dài",
        LIMIT_FIELD_COUNT: "Quá Nhiều Trường",
        LIMIT_UNEXPECTED_FILE: "Trường Không Mong Đợi",
        ONLY_EIGHT_IMAGES: "Chỉ Cho Phép Tải Lên 8 Ảnh",
        CAR_STATUS_HAS_BEEN_UPDATED_BEFORE:
            "Trạng Thái Xe Đã Được Cập Nhật Trước Đó",
        MISSING_FIELD_NAME: "Thiếu Tên Trường",
        ONLY_SUPPORT_IMAGE: "Chỉ Hỗ Trợ Tệp Hình Ảnh",
        ERROR_UPLOAD_IMAGE: "Lỗi Tải Ảnh",
        ERROR_NO_PICTURE: "Lỗi Không Có Hình Ảnh",
        LICENSE_PLATES_EXIST: "Biển Số Xe Đã Tồn Tại",
        DATA_IS_UNCHANGED: "Dữ Liệu Không Thay Đổi",
        CURRENTLY_UNABLE_TO_UPDATE: "Hiện Không Thể Cập Nhật",
        SUPPORT_LENGTH_LICENSE_PLATES: `Biển Số Từ ${Constants.Common.CHARACTERS_MIN_LENGTH_LICENSE_PLATES} - ${Constants.Common.CHARACTERS_MAX_LENGTH_LICENSE_PLATES} Ký Tự`,
        CODE_USER_ALREADY_EXISTS: "Mã Người Dùng Đã Tồn Tại",
        EMAIL_USER_ALREADY_EXISTS: "Email Người Dùng Đã Tồn Tại",
        SUPPORT_FULL_NAME: `Tên Từ ${Constants.Common.MIN_LENGTH_FULL_NAME} - ${Constants.Common.MAX_LENGTH_FULL_NAME} Ký Tự`,
        SUPPORT_CODE: `Mã Gồm ${Constants.Common.MAX_LENGTH_CODE} Ký Tự`,
        SUPPORT_EMAIL: `Email Không Đúng Định Dạng`,
        SUPPORT_PASSWORD: `Mật Khẩu Từ ${Constants.Common.MIN_LENGTH_PASSWORD} - ${Constants.Common.MAX_LENGTH_PASSWORD} Ký Tự`,
        SUPPORT_PHONE: `Số Điện Thoại Không Đúng Định Dạng`,
        SUPPORT_LENGTH_MAINTENANCE_DESCRIPTION: `Chỉ cho phép nhập mô tả dưới ${Constants.Common.MAX_LENGTH_MAINTENANCE_DESCRIPTION}`,
    },
};

module.exports = {
    Strings,
};
